### ISSUE TITLE
WP widget: file not recognised

### ISSUE THREAD

**Issue by TrevorHaynes** [thehelvetian/wp-attachment-export#1]
Error msg

Import WordPress
Sorry, there has been an error.
This does not appear to be a WXR file, missing/invalid WXR version number

**Comment by thehelvetian** [comment]
Hello Trevor,

thanks for reporting the issue. I doubt that is has something to do with the plugin as the issue is well known with the WordPress importer itself. Please check the following:
- Open the XML file in a text editor and make sure there is a line `<wp:wxr_version>1.1</wp:wxr_version>` after the `<channel>` section near the top (version number may differ).
- Make sure WordPress has write permissions in `wp-content/uploads`. You can temporarily `chmod 777` the uploads folder & it's children to make sure although `chmod 755` should work.
- Some users reported issues with `PHP safe_mode` on the server. Turn it off.
- It could be a file encoding issue. [Converting](https://kb.iu.edu/d/acux) the file to Unix newline seems to fix it.

Let me know if any of these helped, good luck!

**Comment by TrevorHaynes** [comment]
Thanks for this, but I'm running the original site on wordpress.com, and thus have no access to these files.  I've uploaded the originals by FTP to the new server, and imported them with the "add from server" plug-in.  Time consuming but that's WP.

**Comment by thehelvetian** [comment]
Ah man what a pita. Glad you figured it out somehow anyway.
